-- SQLite schema
CREATE TABLE IF NOT EXISTS contacts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL,
  message TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(190) NOT NULL,
  category VARCHAR(120) NOT NULL,
  image_url VARCHAR(255),
  project_url VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
